load("//:cross_scala.bzl", "scala_cross_library")

scala_cross_library(
    name = "transversers",
    srcs = glob([
        "shared/src/main/scala/**/*.scala",
        "jvm/src/main/scala/**/*.scala",
    ]),
    scala_deps = [
        "//scalameta/common",
        "//scalameta/trees",
    ],
    visibility = ["//visibility:public"],
)
