#!/bin/bash
# Verify Bazel setup for Scalameta

set -e

echo "==================================="
echo "Scalameta Bazel Setup Verification"
echo "==================================="
echo

# Check Bazel is installed
echo "Checking Bazel installation..."
if command -v bazel &> /dev/null; then
    BAZEL_VERSION=$(bazel version | grep "Build label" | awk '{print $3}')
    echo "✓ Bazel found: $BAZEL_VERSION"
else
    echo "✗ Bazel not found. Please install Bazel 8.x or later."
    exit 1
fi
echo

# Check Java version
echo "Checking Java installation..."
if command -v java &> /dev/null; then
    JAVA_VERSION=$(java -version 2>&1 | head -n 1 | awk -F '"' '{print $2}')
    echo "✓ Java found: $JAVA_VERSION"
else
    echo "✗ Java not found. Please install Java 11 or later."
    exit 1
fi
echo

# Check for required files
echo "Checking Bazel configuration files..."
FILES=(
    "WORKSPACE"
    "MODULE.bazel"
    ".bazelrc"
    "semanticdb/semanticdb/BUILD.bazel"
    "scalameta/common/BUILD.bazel"
    "scalameta/scalameta/BUILD.bazel"
)

for file in "${FILES[@]}"; do
    if [ -f "$file" ]; then
        echo "✓ Found: $file"
    else
        echo "✗ Missing: $file"
        exit 1
    fi
done
echo

# Check for source directories
echo "Checking source directories..."
DIRS=(
    "scalameta/common/shared/src/main/scala"
    "scalameta/io/shared/src/main/scala"
    "scalameta/dialects/shared/src/main/scala"
    "scalameta/inputs/shared/src/main/scala"
    "scalameta/tokens/shared/src/main/scala"
    "scalameta/tokenizers/shared/src/main/scala"
    "scalameta/trees/shared/src/main/scala"
    "scalameta/transversers/shared/src/main/scala"
    "scalameta/parsers/shared/src/main/scala"
    "scalameta/quasiquotes/shared/src/main/scala"
    "scalameta/scalameta/shared/src/main/scala"
)

for dir in "${DIRS[@]}"; do
    if [ -d "$dir" ]; then
        echo "✓ Found: $dir"
    else
        echo "⚠ Missing: $dir (this might be expected)"
    fi
done
echo

# Check for protobuf files
echo "Checking protobuf setup..."
if [ -f "semanticdb/semanticdb/semanticdb.proto" ]; then
    echo "✓ Found: semanticdb.proto"
else
    echo "✗ Missing: semanticdb.proto"
fi

if [ -d "semanticdb/semanticdb/jvm/target/scala-2.13/src_managed" ]; then
    echo "✓ Found: protobuf generated files"
    echo "  (Generated by sbt)"
else
    echo "⚠ Missing: protobuf generated files"
    echo "  Run 'sbt semanticdbJVM/compile' to generate them"
fi
echo

# Try syncing dependencies
echo "Testing dependency sync..."
if bazel sync 2>&1 | grep -q "ERROR"; then
    echo "✗ Dependency sync failed"
    echo "  Check WORKSPACE configuration"
else
    echo "✓ Dependencies synced successfully"
fi
echo

# Try querying a target
echo "Testing Bazel query..."
if bazel query "//scalameta/common:common" &> /dev/null; then
    echo "✓ Bazel query works"
else
    echo "✗ Bazel query failed"
    echo "  Check BUILD.bazel files"
fi
echo

echo "==================================="
echo "Verification Summary"
echo "==================================="
echo
echo "Status: Setup verification complete"
echo
echo "Next steps:"
echo "1. Generate protobuf files: sbt semanticdbJVM/compile"
echo "2. Try building: bazel build //scalameta/common"
echo "3. Build main target: bazel build //scalameta/scalameta:scalameta"
echo
echo "For more information, see:"
echo "- BAZEL_README.md"
echo "- BAZEL_QUICKSTART.md"
echo "- BAZEL_MIGRATION_PROGRESS.md"
echo
