// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package scala.meta.internal.semanticdb3.semanticdb3

@SerialVersionUID(0L)
final case class TypeType(
    typeParameters: _root_.scala.Option[scala.meta.internal.semanticdb3.semanticdb3.Scope] = None,
    lowerBound: scala.meta.internal.semanticdb3.semanticdb3.Type = scala.meta.internal.semanticdb3.semanticdb3.Type.Empty,
    upperBound: scala.meta.internal.semanticdb3.semanticdb3.Type = scala.meta.internal.semanticdb3.semanticdb3.Type.Empty
    ) extends scala.meta.internal.semanticdb3.semanticdb3.Type with scalapb.GeneratedMessage with scalapb.Message[TypeType] with scalapb.lenses.Updatable[TypeType] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      if (typeParameters.isDefined) {
        val __value = typeParameters.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (lowerBound.isDefined) {
        val __value = lowerBound.asTypeMessage
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (upperBound.isDefined) {
        val __value = upperBound.asTypeMessage
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size
    }
    final override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      if (lowerBound.isDefined) { 
        val __m = lowerBound.asTypeMessage
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      if (upperBound.isDefined) { 
        val __m = upperBound.asTypeMessage
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      typeParameters.foreach { __v =>
        val __m = __v
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): scala.meta.internal.semanticdb3.semanticdb3.TypeType = {
      var __typeParameters = this.typeParameters
      var __lowerBound = this.lowerBound
      var __upperBound = this.upperBound
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 34 =>
            __typeParameters = Option(_root_.scalapb.LiteParser.readMessage(_input__, __typeParameters.getOrElse(scala.meta.internal.semanticdb3.semanticdb3.Scope.defaultInstance)))
          case 18 =>
            __lowerBound = _root_.scalapb.LiteParser.readMessage(_input__, __lowerBound.asTypeMessage).value
          case 26 =>
            __upperBound = _root_.scalapb.LiteParser.readMessage(_input__, __upperBound.asTypeMessage).value
          case tag => _input__.skipField(tag)
        }
      }
      scala.meta.internal.semanticdb3.semanticdb3.TypeType(
          typeParameters = __typeParameters,
          lowerBound = __lowerBound,
          upperBound = __upperBound
      )
    }
    def getTypeParameters: scala.meta.internal.semanticdb3.semanticdb3.Scope = typeParameters.getOrElse(scala.meta.internal.semanticdb3.semanticdb3.Scope.defaultInstance)
    def clearTypeParameters: TypeType = copy(typeParameters = None)
    def withTypeParameters(__v: scala.meta.internal.semanticdb3.semanticdb3.Scope): TypeType = copy(typeParameters = Option(__v))
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 4 => typeParameters.orNull
        case 2 => {
          val __t = lowerBound
          if (__t != scala.meta.internal.semanticdb3.semanticdb3.Type.defaultInstance) __t else null
        }
        case 3 => {
          val __t = upperBound
          if (__t != scala.meta.internal.semanticdb3.semanticdb3.Type.defaultInstance) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 4 => typeParameters.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => lowerBound.asTypeMessage.toPMessage
        case 3 => upperBound.asTypeMessage.toPMessage
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = scala.meta.internal.semanticdb3.semanticdb3.TypeType
}

object TypeType extends scalapb.GeneratedMessageCompanion[scala.meta.internal.semanticdb3.semanticdb3.TypeType] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[scala.meta.internal.semanticdb3.semanticdb3.TypeType] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, _root_.scala.Any]): scala.meta.internal.semanticdb3.semanticdb3.TypeType = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    scala.meta.internal.semanticdb3.semanticdb3.TypeType(
      __fieldsMap.get(__fields.get(0)).asInstanceOf[_root_.scala.Option[scala.meta.internal.semanticdb3.semanticdb3.Scope]],
      __fieldsMap.getOrElse(__fields.get(1), scala.meta.internal.semanticdb3.semanticdb3.Type.defaultInstance).asInstanceOf[scala.meta.internal.semanticdb3.semanticdb3.Type],
      __fieldsMap.getOrElse(__fields.get(2), scala.meta.internal.semanticdb3.semanticdb3.Type.defaultInstance).asInstanceOf[scala.meta.internal.semanticdb3.semanticdb3.Type]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[scala.meta.internal.semanticdb3.semanticdb3.TypeType] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      scala.meta.internal.semanticdb3.semanticdb3.TypeType(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).flatMap(_.as[_root_.scala.Option[scala.meta.internal.semanticdb3.semanticdb3.Scope]]),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[scala.meta.internal.semanticdb3.semanticdb3.Type]).getOrElse(scala.meta.internal.semanticdb3.semanticdb3.Type.defaultInstance),
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[scala.meta.internal.semanticdb3.semanticdb3.Type]).getOrElse(scala.meta.internal.semanticdb3.semanticdb3.Type.defaultInstance)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Semanticdb3Proto.javaDescriptor.getMessageTypes.get(19)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Semanticdb3Proto.scalaDescriptor.messages(19)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 4 => __out = scala.meta.internal.semanticdb3.semanticdb3.Scope
      case 2 => __out = scala.meta.internal.semanticdb3.semanticdb3.Type.Message
      case 3 => __out = scala.meta.internal.semanticdb3.semanticdb3.Type.Message
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = scala.meta.internal.semanticdb3.semanticdb3.TypeType(
  )
  implicit class TypeTypeLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, scala.meta.internal.semanticdb3.semanticdb3.TypeType]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, scala.meta.internal.semanticdb3.semanticdb3.TypeType](_l) {
    def typeParameters: _root_.scalapb.lenses.Lens[UpperPB, scala.meta.internal.semanticdb3.semanticdb3.Scope] = field(_.getTypeParameters)((c_, f_) => c_.copy(typeParameters = Option(f_)))
    def optionalTypeParameters: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[scala.meta.internal.semanticdb3.semanticdb3.Scope]] = field(_.typeParameters)((c_, f_) => c_.copy(typeParameters = f_))
    def lowerBound: _root_.scalapb.lenses.Lens[UpperPB, scala.meta.internal.semanticdb3.semanticdb3.Type] = field(_.lowerBound)((c_, f_) => c_.copy(lowerBound = f_))
    def upperBound: _root_.scalapb.lenses.Lens[UpperPB, scala.meta.internal.semanticdb3.semanticdb3.Type] = field(_.upperBound)((c_, f_) => c_.copy(upperBound = f_))
  }
  final val TYPE_PARAMETERS_FIELD_NUMBER = 4
  final val LOWER_BOUND_FIELD_NUMBER = 2
  final val UPPER_BOUND_FIELD_NUMBER = 3
}
